apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
spec:
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      containers:
      - name: todo-app-backend
        image: adamandika/server-js:latest
        env:
          - name: MONGO_URL
            value: "mongodb://mongodb-service.default:27017"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        
