apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc-production
  namespace: production
spec:
  selector:
    app: todo-app-backend-production
  type: NodePort
  
  ports:
    - port: 4000
      targetPort: 4000