apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-staging
  namespace: staging
spec:
  selector:
    matchLabels:
      app: todo-app-backend-staging
  template:
    metadata:
      labels:
        app: todo-app-backend-staging
    spec:
      containers:
      - name: todo-app-backend-staging
        image: adamandika/server-js:latest
        env:
          - name: MONGO_URL
            value: "mongodb://mongodb-service:27017"
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 4000
        
