apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc-staging
  namespace: staging
spec:
  selector:
    app: todo-app-backend-staging
  type: NodePort
  
  ports:
    - port: 4000
      targetPort: 4000